<?php


function cu_saml_module_implements_alter(&$implementations, $hook) {

  if ($hook == 'user_logout') {
    $group = array('cu_saml' => $implementations['cu_saml']);
    unset($implementations['cu_saml']);
    $implementations = $group + $implementations;
    //array_unshift($implementations, $group);
  }

}

function cu_saml_user_logout($account) {
  session_destroy();
  print_r('in hook logout');
  return new RedirectResponse(\Drupal::url('user.page'));
}
